# -*- coding: utf-8 -*-
"""Generate arithmetic problems

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVGOWYDmBbzQsviuW3ambc49W4azkdDv
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install python-docx

from typing import List, Dict
import json
import google.generativeai as genai
from docx import Document
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_TAB_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE
from time import sleep
from dotenv import load_dotenv
import os
import argparse
import re  # Add this to imports at the top

# Load environment variables from .env file
load_dotenv()

# --- Configure the Gemini API ---
API_KEY = os.getenv('GOOGLE_API_KEY')
if not API_KEY:
    raise ValueError("GOOGLE_API_KEY not found in environment variables")
genai.configure(api_key=API_KEY)

def generate_word_problems(problem_count: int, number_limit: int, api_attempts: int, temperature: float = 0.9) -> List[Dict]:
    prompt_text = f"""
Generate a JSON array containing exactly {problem_count} word problems designed for a primary school student learning basic addition and subtraction.

Each problem should be:
1.  A simple, single-step addition or subtraction.
2.  Use numbers (including the result) strictly within the range of 0 to {number_limit}.
3.  Easy for a young child to understand, but interesting and fun.
4.  Feature different objects, scenarios, or characters where possible to add variety. Use wacky names and objects.
5.  Spell numbers out as words in the question. Do not use digits. (For example, write "fifteen" not "15".)
6.  Don't repeat the same names or objects as in the examples in the prompt.

The output should be a JSON array where each element is an object with two keys:
-   `"question"`: The full text of the word problem.
-   `"answer"`: A concluding sentence for the problem with a blank space `____________` where the numerical answer should go. Do NOT include the actual number in the answer field.

Follow this JSON format exactly:
[
  {{"question": "Bob had five slap bands. His mum gave him one more. How many does he have now?", "answer": "Bob now has ____________ slap bands."}},
  {{"question": "Tom saw ten monkeys in a tree. Then, two monkeys ran away. How many monkeys are on the tree now?", "answer": "There are now ____________ monkeys on the tree."}},
  {{"question": "Mia picked six flowers then gave two of them to her sister. How many flowers does she have left?", "answer": "Mia has ____________ flowers left."}}
]
"""
    for _ in range(api_attempts):
        word_problems = []
        try:
            model = genai.GenerativeModel('gemini-2.0-flash')
            generation_config = {
                "temperature": temperature,
                "top_p": 0.8,
                "top_k": 40
            }
            response = model.generate_content(
                prompt_text,
                generation_config=generation_config
            )
            response_text = response.text.strip()
            json_start = response_text.find('[')
            json_end = response_text.rfind(']') + 1

            if json_start != -1 and json_end != -1 and json_end > json_start:
                json_data_string = response_text[json_start:json_end]
                word_problems = json.loads(json_data_string)
                return word_problems
            else:
                print("Could not find valid JSON data in the API response.")
                print("API Response:", response_text)
        except Exception as e:
            print(f"An error occurred during the API call or JSON processing: {e}")
        sleep(30)
    return []

def make_worksheet(number: int, problem_count: int, number_limit: int, api_attempts: int, temperature: float = 0.9) -> str:
    filename = f"add_sub_word_problems_{number}.docx"
    word_problems = generate_word_problems(problem_count, number_limit, api_attempts, temperature)
    print(f"*** Worksheet #{number} ***")
    for i, p in enumerate(word_problems, 1):
        print(f"{i}. {p['question']}")
        print(f"   {p['answer']}")
    print()

    if not word_problems:
        raise Exception("Failed to generate word problems")

    document = Document()
    section = document.sections[0]
    section.page_height = Cm(29.7)  # A4 height in cm
    section.page_width = Cm(21.0)   # A4 width in cm

    styles = document.styles
    normal_style = styles['Normal']
    normal_style.font.size = Pt(14)

    section = document.sections[0]
    section.top_margin = Inches(0.5)
    section.bottom_margin = Inches(0.5)
    section.left_margin = Inches(0.5)
    section.right_margin = Inches(0.5)

    document.add_heading(f'Arithmetic problem set {number}', 0)

    for i, problem in enumerate(word_problems):
        p = document.add_paragraph(f"{problem['question']}\n", style='List Number')
        p.add_run(f"Number sentence: {'_'*70}\n")
        # widen the answer field
        ans = ('_'*40).join(re.split(r'_+', problem['answer']))
        p.add_run(f"Answer: {ans}\n")

    document.save(filename)
    print(f"Word document '{filename}' created successfully.")
    return filename

def main():
    parser = argparse.ArgumentParser(
        description='Generate arithmetic word problem worksheets',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        'number',
        type=int,
        help='Worksheet number to generate'
    )
    parser.add_argument(
        '--problem-count',
        type=int,
        default=7,
        help='Number of problems to generate per worksheet'
    )
    parser.add_argument(
        '--number-limit',
        type=int,
        default=15,
        help='Maximum number to use in problems'
    )
    parser.add_argument(
        '--api-attempts',
        type=int,
        default=3,
        help='Number of API attempts before giving up'
    )
    parser.add_argument(
        '--output-dir',
        type=str,
        default='.',
        help='Directory to save the generated worksheets'
    )
    parser.add_argument(
        '--temperature',
        type=float,
        default=0.9,
        help='Temperature for LLM generation (0.0 to 1.0, higher means more creative)'
    )

    args = parser.parse_args()

    try:
        filename = make_worksheet(
            number=args.number,
            problem_count=args.problem_count,
            number_limit=args.number_limit,
            api_attempts=args.api_attempts,
            temperature=args.temperature
        )
        print(f"Successfully generated worksheet {args.number} as {filename}")
    except Exception as e:
        print(f"Error generating worksheet: {e}")
        exit(1)

if __name__ == '__main__':
    main()
